default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.6
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: fix-compose-imports
        name: Fix compose imports
        entry: uv run fix-compose-imports
        language: system
        types: [python]
