name: Load python cache
description: Load python cache

inputs:
  python-version:
    description: Python version to use
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Load cached poetry installation
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-${{ inputs.python-version }}

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
