services:
  app:
    container_name: compose-sql-example-app
    build:
      context: ../..
      dockerfile: examples/sql_example/docker/Dockerfile
    platform: linux/amd64
    image: compose-sql-example-app:latest
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - APP_ENV=local
    ports:
      - "8000:8000"
    volumes:
      - .:/app/examples/sql_example
      - ../../compose:/app/compose
