services:
  api:
    container_name: compose-fastapi-example-api
    build:
      context: ../..
      dockerfile: examples/fastapi_example/docker/Dockerfile
    platform: linux/amd64
    image: compose-fastapi-example-api:latest
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload --proxy-headers
    environment:
      - APP_ENV=local
    volumes:
      - .:/app/examples/fastapi_example
      - ../../compose:/app/compose
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: compose-fastapi-example-db
    image: mongo:8
    platform: linux/arm64/v8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    restart: unless-stopped
