name: Run tests

on:
  workflow_call:
    inputs:
      python-version:
        type: string
      unit:
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.2"
          cache-dependency-glob: "uv.lock"

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Run tests
        run: |
          uv run pytest -vv -s tests -m ${{ inputs.unit }}
