name: Test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    strategy:
      matrix:
        python-version: [3.12, 3.13]

    uses: ./.github/workflows/unit-test.yml
    secrets: inherit
    with:
      python-version: ${{ matrix.python-version }}
      uv-version: "0.6.6"

  integration-test:
    strategy:
      matrix:
        python-version: [3.12, 3.13]

    uses: ./.github/workflows/integration-test.yml
    secrets: inherit
    with:
      python-version: ${{ matrix.python-version }}
      uv-version: "0.6.6"
    