name: Test

on:
  pull_request:
    branches:
      - main
      - v1*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit
