name: Test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    strategy:
      matrix:
        python-version: [3.12, 3.13, 3.14]

    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      python-version: ${{ matrix.python-version }}

  integration-test:
    strategy:
      matrix:
        python-version: [3.12, 3.13, 3.14]

    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      python-version: ${{ matrix.python-version }}
