name: Run unit tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
      fail-fast: false

    name: Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - uses: POZAlabs/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: "2.0.1"
          setup-command: |
            poetry install --all-extras --no-interaction

      - name: Run tests
        run: |
          poetry run pytest -vv -s tests -m unit
