name: Run unit tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
        pydantic-version:
          - "^1.10.13"
          - "^2.3.0"
      fail-fast: false

    name: Python ${{ matrix.python-version }} / pydantic ${{ matrix.pydantic-version }}

    steps:
      - uses: actions/checkout@v3

      - uses: POZAlabs/actions/.github/actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install extra dependencies
        run: poetry install --all-extras

      - name: Install pydantic ${{ matrix.pydantic-version }}
        run: poetry add pydantic@${{ matrix.pydantic-version }}

      - name: Run unit tests
        run: |
          poetry run pytest -vv -s tests
