name: Run unit tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.10"
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run unit tests
        run: |
          poetry run pytest -vv -s tests
        env:
          APP_ENV: test
