name: Update Python Cache

on:
  push:
    branches:
      - main

jobs:
  update-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - uses: POZAlabs/actions/.github/actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
