name: Update Python Cache

on:
  push:
    branches:
      - main

jobs:
  update-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: POZAlabs/actions/.github/actions/setup-python@v1-beta
        with:
          python-version: ${{ matrix.python-version }}
          setup-command: |
            poetry install --all-extras --no-interaction
